name: Build and Push NuGet Packages

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/publish.yaml
      - src/**/*
      - Directory.Build.props
      - Directory.Packages.props
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - .github/workflows/publish.yaml
      - src/**/*
      - Directory.Build.props
      - Directory.Packages.props
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      packages: write

    env:
      SOLUTION: "BiUM.slnx"
      BUILD_CONFIG: "Release"
      MAJOR: 1
      MINOR: 5
      MINOR_START_RUN: 91

    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Get .NET Version from Directory.Build.props
        id: dotnet_version
        run: |
          # 1. Grep the line, extracting only the matched segment
          # 2. Sed capture group to get the digit after 'net'
          MAJOR_VERSION=$(grep -oP '<TargetFramework>.*</TargetFramework>' Directory.Build.props | sed -E 's/.*net([0-9]+).*/\1/')

          echo "Detected .NET Major Version: $MAJOR_VERSION"

          # 3. Write to GitHub Output
          echo "major=$MAJOR_VERSION" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.dotnet_version.outputs.major }}
          dotnet-quality: "ga"

      - name: Calculate package version
        run: |
          PATCH=$(( ${{ github.run_number }} - MINOR_START_RUN ))

          if [ $PATCH -lt 0 ]; then
            echo "PATCH version negatif olamaz"
            exit 1
          fi

          echo "PACKAGE_VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
          echo "Calculated version: $MAJOR.$MINOR.$PATCH"

      - name: Build
        run: |
          dotnet build \
            $SOLUTION \
            --configuration $BUILD_CONFIG \
            --verbosity minimal \
            --property:Version="$PACKAGE_VERSION" \
            --property:ContinuousIntegrationBuild=true \
            --property:Deterministic=true \
            --property:DeterministicSourcePaths=true \
            --property:SourceLinkCreate=true \
            --property:DebugType=pdbonly \
            --property:IncludeSymbols=true \
            --property:SymbolPackageFormat=snupkg

      - name: Run Tests
        run: |
          dotnet test $SOLUTION \
            --configuration $BUILD_CONFIG \
            --no-restore \
            --no-build \
            --verbosity minimal

      - name: Setup NuGet Source
        if: github.event_name != 'pull_request'
        run: |
          PACKAGE_USER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          PACKAGE_SOURCE=https://nuget.pkg.github.com/$PACKAGE_USER/index.json

          echo "PACKAGE_USER=$PACKAGE_USER" >> $GITHUB_ENV
          echo "PACKAGE_SOURCE=$PACKAGE_SOURCE" >> $GITHUB_ENV

      - name: Add GitHub NuGet Source
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget add source $PACKAGE_SOURCE \
            --name github \
            --username $PACKAGE_USER \
            --password ${{ secrets.SECRET_KEY }} \
            --store-password-in-clear-text

      - name: Publish Packages to GitHub NuGet Source
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push \
            **/*.nupkg \
            --source "github" \
            --api-key ${{ secrets.SECRET_KEY }} \
            --skip-duplicate

      - name: Publish Symbols to GitHub NuGet Source
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push \
            **/*.snupkg \
            --source "github" \
            --api-key ${{ secrets.SECRET_KEY }} \
            --skip-duplicate
